INSERT IGNORE INTO vacunas(id,nombre) VALUES (1,"Tuberculosis"),
                                             (2,"Hepatitis"),
                                             (3,"Polio"),
                                             (4,"PENTAVALENTE"),
                                             (5,"Rotavirus"),
                                             (6,"Neumococo"),
                                             (7,"Polio"),
                                             (8,"Influenza"),
                                             (9,"Sarampión rubeola paperas"),
                                             (10,"Fiebre amarilla"),
                                             (11,"Hepatitis A"),
                                             (12,"Difteria-Tosferina-Tétano"),
                                             (13,"Covid-19");